// ============================================
// Mock Data - Pour le développement et la démo
// ============================================

import { Lead, AuditResult, DashboardStats } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    company: "Restaurant Le Parisien",
    website: "https://le-parisien-restaurant.fr",
    contactName: "Jean Dupont",
    contactEmail: "jean@le-parisien.fr",
    phone: "+33 6 12 34 56 78",
    heatScore: 87,
    status: "new",
    createdAt: "2026-03-28T10:00:00Z",
    updatedAt: "2026-03-28T10:00:00Z",
    notes: "Site très ancien, gros potentiel",
  },
  {
    id: "2",
    company: "Plomberie Martin",
    website: "https://plomberie-martin.wixsite.com",
    contactName: "Pierre Martin",
    contactEmail: "pierre@plomberie-martin.fr",
    heatScore: 72,
    status: "contacted",
    createdAt: "2026-03-27T14:00:00Z",
    updatedAt: "2026-03-29T09:00:00Z",
  },
  {
    id: "3",
    company: "Boulangerie Leclerc",
    website: "https://boulangerie-leclerc.fr",
    contactName: "Marie Leclerc",
    contactEmail: "contact@boulangerie-leclerc.fr",
    phone: "+33 6 98 76 54 32",
    heatScore: 54,
    status: "meeting",
    createdAt: "2026-03-25T08:00:00Z",
    updatedAt: "2026-03-30T16:00:00Z",
    notes: "RDV prévu vendredi 14h",
  },
  {
    id: "4",
    company: "Auto-École Conduite+",
    website: "https://conduite-plus.fr",
    contactName: "Ahmed Benali",
    contactEmail: "ahmed@conduite-plus.fr",
    heatScore: 91,
    status: "new",
    createdAt: "2026-03-30T12:00:00Z",
    updatedAt: "2026-03-30T12:00:00Z",
    notes: "Site WordPress très lent, plugins outdated",
  },
  {
    id: "5",
    company: "Studio Photo Lumière",
    website: "https://studio-lumiere.com",
    contactName: "Sophie Durand",
    contactEmail: "sophie@studio-lumiere.com",
    heatScore: 38,
    status: "proposal",
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-31T11:00:00Z",
  },
  {
    id: "6",
    company: "Garage Auto Express",
    website: "https://garage-auto-express.fr",
    contactName: "Luc Moreau",
    contactEmail: "luc@garage-express.fr",
    heatScore: 65,
    status: "contacted",
    createdAt: "2026-03-26T15:00:00Z",
    updatedAt: "2026-03-28T10:00:00Z",
  },
  {
    id: "7",
    company: "Cabinet Dentaire Sourire",
    website: "https://cabinet-sourire.fr",
    contactName: "Dr. Claire Petit",
    contactEmail: "contact@cabinet-sourire.fr",
    heatScore: 79,
    status: "new",
    createdAt: "2026-03-31T09:00:00Z",
    updatedAt: "2026-03-31T09:00:00Z",
  },
  {
    id: "8",
    company: "Fleuriste Rosalie",
    website: "https://rosalie-fleurs.fr",
    contactName: "Nathalie Rose",
    contactEmail: "nathalie@rosalie-fleurs.fr",
    heatScore: 45,
    status: "signed",
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-25T14:00:00Z",
    notes: "Contrat signé - Refonte complète",
  },
];

export const mockAuditResult: AuditResult = {
  url: "https://le-parisien-restaurant.fr",
  timestamp: new Date().toISOString(),
  lighthouse: {
    performance: 32,
    accessibility: 58,
    bestPractices: 45,
    seo: 52,
  },
  seo: {
    title: "Le Parisien",
    titleLength: 11,
    metaDescription: "",
    metaDescriptionLength: 0,
    h1Count: 0,
    h1Tags: [],
    h2Count: 2,
    imgWithoutAlt: 8,
    totalImages: 12,
    hasCanonical: false,
    hasRobotsTxt: false,
    hasSitemap: false,
    hasOpenGraph: false,
    hasTwitterCard: false,
    internalLinks: 5,
    externalLinks: 1,
    brokenLinks: ["/menu-pdf", "/gallery/photos"],
  },
  techStack: {
    framework: null,
    cms: "WordPress 5.2",
    jsLibraries: ["jQuery 1.12.4", "Bootstrap 3.3.7"],
    cssFramework: "Bootstrap",
    analytics: [],
    cdn: null,
    server: "Apache/2.4.29",
    outdatedLibraries: [
      {
        name: "jQuery",
        version: "1.12.4",
        issue: "Vulnérabilité XSS connue (CVE-2020-11022)",
        severity: "critical",
      },
      {
        name: "Bootstrap",
        version: "3.3.7",
        issue: "XSS dans data-target (CVE-2018-14041)",
        severity: "high",
      },
      {
        name: "WordPress",
        version: "5.2",
        issue: "Multiple vulnérabilités de sécurité non corrigées",
        severity: "critical",
      },
    ],
  },
  security: {
    https: false,
    hsts: false,
    mixedContent: true,
    outdatedLibraries: 3,
    xFrameOptions: false,
    contentSecurityPolicy: false,
  },
  overall: 87,
};

export const mockDashboardStats: DashboardStats = {
  totalLeads: 8,
  hotLeads: 4,
  contactedToday: 2,
  conversionRate: 12.5,
  avgHeatScore: 66,
};
